### ISSUE TITLE
Quality Score for Face Between 0 -100

### ISSUE THREAD

**Issue by JanardhanBS-SyncByte** [Biometix/bqat-stateless#1]
5.4.8 Quality Score
The (1 byte) Quality Score, as defined in ISO/IEC 29794-1, shall be a quantitative expression of the predicted
verification performance of the biometric sample. Valid values for Quality Score are integers between 0 and
100, where higher values indicate better quality.

**Comment by lw0404** [comment]
This will come with the next update.
